name: Release

on:
  push:
    tags:
    - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Changelog
        run: |
          cl="$(cat CHANGES.md | sed '1,/## /d' | sed -n '/## /q;p')"
          cl="${cl//'%'/'%25'}"
          cl="${cl//$'\n'/'%0A'}"
          cl="${cl//$'\r'/'%0D'}"
          echo "$cl" > CHANGELOG.md
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
